<?php
header("Content-Type: text/html;charset=utf-8");
//CADENAS UTILIZADAS EN CASTELLANO
$strings = array(

//MENSAJES BASE DE DATOS
 'Fallo al conectar a MySQL: (' => 'Fail to connect to MySQL',
 'La contraseña para este usuario es errónea' => 'The password for this user is wrong',
 'El usuario no existe' => 'This User does not exist',
 'El usuario ya existe' => 'User already exists',
 'No se ha podido conectar con la base de datos' => 'Unable to connect to the database',
 'Inserción realizada con éxito' => 'Insertion made successfully',
 'El usuario ya existe en la base de datos' => 'This user already exists in the database',
 'Introduzca un valor para username del usuario' => 'Enter a value for the user`s username',
 'Error en la consulta sobre la base de datos' => 'Error in the query on the database',
 'El usuario se ha modificado con éxito' => 'The user has been modified successfully',
 'El usuario ha sido borrado correctamente' => 'The user has been deleted correctly',
 'Ya existe un Usuario con ese userName' => 'A User already exists with that userName',
 'Ya existe un Usuario con ese DNI' => 'There is already a User with this DNI',
 'Ya existe un Usuario con ese E-mail' => 'There is already a User with that E-mail',
 'No se ha podido conectar con la base de datos.' => 'Could not connect to the database.',
 'Error en la consulta sobre la base de datos.' => 'Error in the query on the database.',
 'No se puede borrar porque no existe esa Alerta.' => 'It can not be deleted because that Alert does not exist.',
 'La Alerta fue borrada con éxito.' => 'The Alert was erased successfully.',
 'No tienes los permisos necesarios' => 'You do not have the necessary permits',
 'No se importó correctamente porque no se seleccionó ningún curso' => 'It was not imported correctly because no course was selected',
 'Debe seleccionar un Curso' => 'You must select a Course',
 'NumSesiones' => 'Number of Calendars',
 'Error: ya existe un calendario con ese nombre.' => 'Error: A calendar with that name already exists.',
 'Asignaturas asignadas correctamente.' => 'Subjects assigned correctly.',
 'Asignaturas eliminadas correctamente.' => 'Subjects deleted correctly.',
 'Calendario modificado correctamente.' => 'Calendar modified correctly.',
 'Calendario eliminado correctamente.' => 'Calendar successfully deleted.',
 'Error al insertar en tabla calendario_evento.' => 'Error inserting event in calendar.',
 'tituloPU' => 'Are you sure?',
 'textoPU' => 'Once deleted, you will not be able to recover this register!',
 'botonCancel' => 'Cancel',
 'botonOk' => 'Confirm',
 'El calendario se ha modificado con éxito.' => 'The calendar has been modified successfully.',
 'Modificación realizada con éxito' => 'Modification made successfully',
 'Éste evento ya existe' => 'This event already exists',
 'Acerca de UniOrganizer' => 'About UniOrganizer',
 'Aplicación para facilitar la gestión y organización a estudiantes universitarios.' => 'Application to facilitate the management and organization of university students.',
 'Contacto' => 'Contact',

//MENU
 'Iniciar Sesion' => 'Log in',
 'Registrar' => 'Register',
 'Usuario' => 'User',
 'Cerrar Sesión' => 'Sign off',
 'Cuenta' => 'Account',
 'Mi Perfil' => 'My profile',
 'Gestión de Usuarios' => 'Users',
 'Gestión de Alertas' => 'Alerts',
 'Gestión de Eventos' => 'Events',
 'Gestión de Asignaturas' => 'Subjects',
 'Gestión de Calendarios' => 'Calendars',
 'Calendario' => 'Calendar',
 'Gestionar' => 'Manage',
 'Información' => 'Information',

//Templates
'Vista Principal' => 'Main View',
'Crear Alerta' => 'Create Alert',
'Editar Alerta' => 'Edit Alert',
'Lista Asignaturas' => 'List of Subjects',
'Lista Calendarios' => 'Calendars List',
'Crear Calendario' => 'Create Calendar',
'Editar Calendario' => 'Edit Calendar',
'Filtrar Calendarios' => 'Filter Calendars',
'Crear Evento' => 'Create Event',
'Editar Evento' => 'Edit Event',
'Filtrar Eventos' => 'Filter Events',
'Lista Eventos' => 'Events List',
'Crear Usuario' => 'Create User',
'Editar Usuario' => 'Edit User',
'Ver Usuario' => 'See User',
'Lista Usuarios' => 'Users List',
 
//Acciones
 'Volver' => 'Return',
 'Insertar' => 'Insert',
 'Añadir' => 'Add',
 'Modificar' => 'Modify',
 'Consultar' => 'Consult',
 'Borrar' => 'Delete',
 'Ver' => 'Watch',
 'Seleccionar' => 'Select',
 'Cerrar' => 'Close',
 'Guardar' => 'Save',
 'Asignar' => 'Assign',
 'ver' => 'Watch',
 'Inicio' => 'Main View',
 
//USUARIOS
 'username' => 'User',
 'password' => 'Password',
 'newPassword' => 'New password',
 'nombre' => 'Name',
 'apellidos' => 'Surnames',
 'tipoUsuario' => 'User Type',
 'dni' => 'ID',
 'niu' => 'NIU',
 'fechaNac' => 'Birth date',
 'email' => 'E-mail',
 'addAdministrador' => 'Add Administrator',
 'Administrador' => 'Administrator',
 'Estudiante' => 'Student',
 'Insertar usuario' => 'Insert User',
 'Insertar Usuario' => 'Insert User',
 'Insertar Administrador' => 'Add Administrator',
 'Modificar Usuario' => 'Modify User',
 'Eliminar Usuario' => 'Delete User',
 'Eliminar Administrador' => 'Remove Administrator',
 'Ver Usuario' => 'See User',
 'Modificar usuario' => 'Modify User',
 

//Alertas
 'alertas' => 'Alerts',
 'idAlerta' => 'ID Alert',
 'fechaHora' => 'Date',
 'asuntoAlerta' => 'Affair',
 'Descripción' => 'Description',
 'descripcionAlerta' => 'Description',
 'Ver Alerta' => 'See Alert',
 'CrearAlerta' => 'New Alert',
 'Insertar Alerta' => 'Create Alert',
 'Modificar Alerta' => 'Modify Event',
 'Añadir Alerta' => 'Create Alert',
 'Borrar Alerta' => 'Delete Event',
 'La alerta fue borrada con éxito.' => 'The alert was successfully deleted',
 'No se ha podido conectar con la base de datos en INSERT calendario_horas.' => 'The Alert could not be created because there is no such day in the calendar.',
 'Asunto' => 'Affair',
 'Fecha' => 'Date',
 'HoraInicio' => 'Start Time',
 'HoraFin' => 'End Time',
 'Dias' => 'Days',
 'Mensaje' => 'Message',
 'Crear' =>'New Alert',
 'Aviso' =>'Enter how many days before you want the system to remind you of this event.',
 'idEvento' =>'Event ID',
 'eliminarSeleccionadas' =>'Delete Selected',

 //Eventos
 'idEvento' => 'Event ID',
 'fechaHora' => 'Date',
 'asuntoEvento' => 'Affair',
 'Descripción' => 'Description',
 'descripcionEvento' => 'Description',
 'Ver Evento' => 'See Event',
 'CrearEvento' => 'New Event',
 'Insertar Evento' => 'Create Event',
 'Modificar Evento' => 'Modify Event',
 'Añadir Evento' => 'Create Event',
 'Borrar Evento' => 'Delete Event',
 'El evento fue borrado con éxito.' => 'The event was successfully deleted',
 'No se ha podido conectar con la base de datos en INSERT calendario_horas.' => 'The Event could not be created because that day does not exist in the calendar.',
 'Asunto' => 'Affair',
 'Fecha' => 'Date',
 'HoraInicio' => 'Start',
 'HoraFin' => 'End',
 'Dias' => 'Days',
 'Mensaje' => 'Message',
 'Aviso' =>'Enter how many days before you want the system to remind you of this event.',
 'curso' => 'Course',
 'asignatura' => 'Subject',
 'Filtrar Eventos' => 'Filter Events',

//Calendario Principal

 'Monday' => 'Monday',
 'Tuesday' => 'Tuesday',
 'Wednesday' => 'Wednesday',
 'Thursday' => 'Thursday',
 'Friday' => 'Friday',
 'Saturday' => 'Saturday',
 'Sunday' => 'Sunday',
 'Anterior Semana' => 'Previous Week',
 'Próxima Semana' => 'Next week',
 'Filtrar' => 'Filter',
 'Refresh' => 'Recharge',
 'Examen' => 'Exam:',
 'nombreCalendario' => 'First name',
 'idCalendario' => 'Calendar ID',
 'Modificar calendario' => 'Modify Calendar',
 'Se ha insertado con éxito' => 'It has been inserted successfully',
 'Iniciar sesion' => 'Log in',
 'IniciarSesion' => 'Log in',

//Asignaturas
 'idAsignatura' => 'Subject ID',
 'nombreAsignatura' => 'Name of the Subject',
 'asignaturanombreCalendario' => 'Subject Name',
 'descripcionAsignatura' => 'Description of the subject',
 'asignaturadescCalendario' => 'Subject Description',
 'saveform' => 'Save',
 'newAsignatura' => 'New Subject',
 'asignaturanombre' => 'Name',
 'asignaturadescripcion' => 'Description',
 'asignaturamodificar' => 'Modify',
 'asignaturaeliminar' => 'Remove',
 'Eliminar Asignatura' => 'Remove Subject',
 'Guia' => 'Teaching guide',
 
//Calendarios
 'Calendario' => 'Calendar',
 'nombreCalendario2' => 'Calendar Name',
 'descripcionCalendario2' => 'Calendar Description',
 'calendarioname' => 'Calendar Name',
 'calendariodesc' => 'Calendar Description',
 'savecalendario' => 'Save',
 'newcalendario' => 'New calendar',
 'obtenerCurso' => 'Import Course',
 'asignarcalendario' => 'Assign Subjects to Calendar',
 'seleccionaCurso' => 'Select the Course from which you want to import only your subjects',
 'seleccionaAsig' => 'Selecciona asignatura de la que vas a importar todos los eventos',
 'ó' => 'or',
 'closecalendario' => 'Close',
 'calendarioname2' => 'Name',
 'calendariodesc2' => 'Description',
 'calendarioasignar' => 'Assign Subjects',
 'calendariomodificar' => 'Modify',
 'calendarioeliminar' => 'Remove',
 'Eliminar Calendario' => 'Delete Calendar',
 'Calendarios' => 'Calendars',
 'nombreCalendario' => 'Calendar Name',
 'descripcionCalendario' => 'Description',
 'AñadirAsignatura' => 'Add Subject',
 'ImportarAsignatura' => 'Import Subject',
 'ImportarCurso' => 'Import Course',
 'AsignarAsignaturas' => 'Add Subjects',
 'EliminarAsignaturas' => 'Remove Subjects',
 'eliminarSelec' => 'Remove Selected',
 'desasignar'=>'Delete Selected',
 'Asignatura'=>'Subject',
 'Guardar'=>'Save',
 'filtrar'=>'Filter',
 'crear'=>'Create',
 'avisoC'=>'*Only the subjects that have an event are displayed.',
 'Filtrar Calendarios'=>'Filter Calendars',
 'VerEventos'=>'See Events'

);

?>